[package]
name = "tf2sc_auth"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.3.1"

lambda_runtime = "0.13.0"
serde = "1"
tokio = { version = "1", features = ["macros"] }
reqwest = { version = "0.12.15", features = ["rustls-tls", "json"], default-features = false }
